### PR TITLE
Update  doc building and deploy

### PR DESCRIPTION
**Pull request by holgern**

### CODE REVIEW

**Comment by glouppe** [comment]
It seems this PR contains files that come originally from the scikit-learn codebase. You are not allowed import them without mentioning the source.

**Comment by holgern** [comment]
Thanks for letting me know, I added a copied from note.

**Comment by glouppe** [comment]
That's not technically enough. You must state the original source, along with the license...

**Comment by holgern** [comment]
Is this sufficient?
```
# Copied from https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/test_script.sh
# The scikit-learn developers.
# License: BSD-style
```

**Comment by glouppe** [comment]
Please. If we are having a discussion, wait for everyone to agree. You merged #854 without waiting for the input you asked from me...

**Comment by holgern** [comment]
Ok, sorry, but I needed to push the build CI so that I can test further, this is quite time consuming..

**Pull request merged**
