### PR TITLE
[MRG+1] update version to 0.4

### LINKED ISSUE #308: Using GaussianProcessRegressor fails for default values
```python
from skopt.learning import GaussianProcessRegressor

dimensions = [(-5.0, 10.0), (0.0, 15.0)]
gpr = GaussianProcessRegressor()
optimizer = Optimizer(
    dimensions=dimensions,
    base_estimator=gpr,
    n_random_starts=1,
    acq_func="EI",
    random_state=0)

optimizer.tell(optimizer.ask(), branin(x_cand))

AttributeError: 'Product' object has no attribute 'gradient_x'
```

### PR DESCRIPTION
**Pull request by fredcallaway**
Fixes #308. I went with 0.4 because that's the highest version in the change log.

### CODE REVIEW

**Comment by betatim** [comment]
What do others think? It solves the problem of pip thinking it already has the version of `master` installed. I am 👍  for this.

Maybe we can add a `(unreleased)` to line 4 of the changelog? If only as a way for us to keep track of which is the latest released version.

**Comment by betatim** [comment]
An alternative would be that in the code we add a third level to the version (`0.3.x`) while we work towards the release of v0.4. My assumption has always been that we only have two digits in the version because the last one is set to zero for releases.

**Comment by glouppe** [comment]
> An alternative would be that in the code we add a third level to the version (0.3.x) while we work towards the release of v0.4

Or `0.4-dev`? Then release `0.4` when `0.4-dev` has matured enough?

**Comment by MechCoder** [comment]
> Or 0.4-dev? Then release 0.4 when 0.4-dev has matured enough?

+1

**Comment by betatim** [comment]
Thanks! And congratulations on your first contribution to scikit-optimize!

**Comment by fredcallaway** [comment]
Haha, hopefully the next one will be a bit more substantive.

**Pull request merged**
