### PR TITLE
[MRG] Add example notebook for checkpoint callback

### PR DESCRIPTION
**Pull request by cschell**
After adding the `CallbackSaver` callback in #665 I figured that a short example would be nice, so here it is. I followed the style of the [store-and-load-results](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/store-and-load-results.ipynb) example, so I hope the format is appropriate.

### CODE REVIEW

**Comment by iaroslav-ai** [comment]
Hey @cschell ,
thank you for the notebook - looks good!

**Comment by iaroslav-ai** [comment]
Looks all good to me. Will merge today or tomorrow if no objections will appear.

**Comment by betatim** [comment]
📋

**Comment by thinker111** [comment]
Hey,bro
 Appreciate your work! @cschell 
 But  I found error when when put objective function into other funciton currently, then it raises PicklingError: Can't pickle <function runv1.<locals>.objective at 0x0000021BFF6EB948>: it's not found as __main__.runv1.<locals>.objective

checkpoint_saver = CheckpointSaver("./checkpoint.pkl", compress=9) 
space  = [          
      Integer(3,10,name='max_depth'),
      Real(0.001, 0.1,name='learning_rate',),
      Integer(200,500,name='n_estimators',),
     ]

@use_named_args(space)
def objective(**params):                                  
    clf=xgb.XGBClassifier(max_depth=params['max_depth'],
                          learning_rate=params['learning_rate'],
                          n_estimators=params['n_estimators'],
                          reg_alpha=params['reg_alpha'],
                          reg_lambda=params['reg_lambda'],)#n_jobs=-1,objective='multi:softmax',seed=np.random.randint(1e9)
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)
    acc=sklearn.metrics.accuracy_score(y_test, predictions)
    return 1-acc

def runv1():    
    res_gp = gp_minimize(objective, space,n_calls=11, 
                              n_random_starts=10,#之前被注释
                               callback=[checkpoint_saver],)
    print("test error=%.4f" % res_gp.fun)

runv1()

Could you help me solve it? 
Thanks!

**Pull request merged**
