### PR TITLE
[MRG] Notebook on hyperparameter optimisation

### PR DESCRIPTION
**Pull request by glouppe**
My attempt at #102

### CODE REVIEW

**Comment by glouppe** [comment]
#113 should be merged first, so that I can remove these ugly casts in the `objective` function.

**Comment by glouppe** [comment]
Rebased and cleaned up, since #113 is merged.

**Comment by MechCoder** [comment]
Awesome!

**Comment by MechCoder** [comment]
Whoops, should we set `n_start=1` and the compare the performance? The first `n_start` iterations really don't tell us anything right?

**Comment by MechCoder** [comment]
I get this when I do that.


index

**Comment by betatim** [comment]
I'm a bit confused what we are discussing, my guess is that this is about setting the starting point to be the same for all of them?

I think we should do something similar to #103 by running the minimisation many times, and highlighting the average performance.

If we stick with `n_start=10` we should try and find an example where you are unlikely to reach the "optimum" in around ten steps. Or we reduce `n_start` but that makes life harder for the models as they have nothing to fit to -> they are returning more or less random samples.

(New issue or should we keep discussing here?)

**Comment by glouppe** [comment]
+1 for showing something to what you did in the other notebook. Otherwise, methods may still be better than others only by chance.

**Pull request merged**
