### PR TITLE
[WIP] Sphinx based documentation

### LINKED ISSUE #428: Sphinx based documentation
Thoughts on switching to sphinx?

Our current documentation system has served us well so far so switching isn't the highest priority. For me personally it would be easier to use sphinx (because other projects use it, so one less tool to use) and we could maybe remove some of the documentation from `skopt.__doc__` etc. There are also nice utilities like sphinx-gallery which people will recognise from other projects.

The reason I am thinking about documentation is that I think we need to structure our examples a bit better/add some links and narrative that tell new people in which order to read them.

Thoughts?

### PR DESCRIPTION
**Pull request by betatim**
Fixes #428 

Getting started with a documentation marathon.

* [ ] module doc strings
* [ ] adapt doc building so sphinx docs are pushed to github.io
* [ ] structure the API docs
* [ ] integrate example notebooks
* [ ] extend quickstart material
* [ ] add two paragraph summary of when skopt is the right tool

### CODE REVIEW

**Comment by betatim** [comment]
If you feel like contributing: the number one place help is needed is adding doc strings to the modules e.g. `skopt/utils.py` etc

**Comment by MechCoder** [comment]
Thanks for starting this. How do I view the rendered documentation?

(https://707-54340642-gh.circle-artifacts.com/0/home/ubuntu/doc/skopt/notebooks/bayesian-optimization.html) corresponds to the original version?

**Comment by betatim** [comment]
At the moment by `git checkout`ing this PR, `pip install sphinx` and `cd docs && make html` 😄 

Figuring out how to make CircleCI build it is on the list of things to do

**Comment by MechCoder** [comment]
Hmm, I think it might work if you add the same lines to `execute.sh` under `build_tools/circle`

**Comment by betatim** [comment]
PRs to this PR welcome. I think this is the only way to overcome the problem of not merging this before it is complete and the fact that by myself I will never finish this.

**Comment by betatim** [comment]
I think we should try and convert our formatting to https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt mostly because there is a sphinx extension that can render this nicely and because it doesn't look horrible as plain text docstring. Open to other ideas.

For methods/functions/classes that are "simple" we can keep a plain doc string, but if we want to document parameters and return values we should adopt the numpy style.

**Comment by betatim** [comment]
Current snapshot: https://712-54340642-gh.circle-artifacts.com/0/tmp/circle-artifacts.Nzi5r9U/index.html

**Comment by betatim** [comment]
Alternative format that works well is the scikit-learn one.

**Comment by betatim** [comment]
@iaroslav-ai what do you think about trimming the `BayesSearchCV` doc string? It contains several references to sklearn classes that don't resolve at the moment. I'd try and shrink it a bit and put a note at the top: "For full details please refer t `GridSearchCV` in sklearn."

**Comment by iaroslav-ai** [comment]
@betatim would be really great if you would try to shrink it a bit, it is quite big indeed!

**Comment by betatim** [comment]
New snapshot: https://721-54340642-gh.circle-artifacts.com/0/tmp/circle-artifacts.kdXLWjd/index.html

(when did we add this much stuff to skopt? Always thought this was a cute little library ... 😄)

**Comment by MechCoder** [comment]
Thanks for your work! What thoughts do you have on integrating the example notebooks? `sphinx-gallery` might be a good option to do that.

**Comment by betatim** [comment]
Having `sphinx-gallery` was one of the reasons I started this move, so yes I think that is the way to go. Was reading the docs and now thinking it only works with python scripts not notebooks? There is also https://github.com/spatialaudio/nbsphinx which adds notebook support more widely (quick start and other introductory stuff could benefit from this).

Can you see a way to use notebooks with gallery?

**Comment by MechCoder** [comment]
nbsphinx seems pretty neat. Why not just use it?

**Comment by betatim** [comment]
> nbsphinx seems pretty neat. Why not just use it?

Wanted to hear some opinions :) I think it isn't as widely used as sphinx-gallery so if there was a way to use gallery that would be better but seems there isn't. Will probably work on this tomorrow a bit. Slow progress.

**Comment by amueller** [comment]
hm my circle CI browser plugin fails to pick up on the build. I guess because the last one failed? Not sure :-/

**Comment by betatim** [comment]
Forgot to add the `nbsphinx` extension to the CI setup script.

Is there a tool (that works well) for converting our docstrings to numpydoc format? It isn't hard but pretty tedious (aka error prone) and feels like it is impossible to keep up with changes made elsewhere :)

In general what do people think about the layout/sections? Was thinking to add a few of the example notebooks as narrative docs after "quick start" (the what is bayes opt one and the BayesSearchCV one). Link to the rest as examples.

**Comment by betatim** [comment]
What should we do with this? Am I the only one who would like to see a new glorious sphinx based future? Realistically I won't ever be able to catch up with the changes to the current docs, so should we abandon this or merge it with some broken docs and then fix them over time? I'm open to suggestions as I've run out of ideas :)

**Comment by glouppe** [comment]
I suppose this PR has stalled. Are there maybe fragments we could still integrate?

(Switching to a better supported documentation generator is still an open issue in my opinion.)

**Comment by betatim** [comment]
I think to get this rolling again we would have to either make a bit effort all together to switch over all the docs in one go or switch over now and then incrementally fixing up the docs that aren't yet transitioned. I think I prefer the second approach, especially as we already have mixed doc string styles so rendering the docs currently is already "a bit broken".

**Comment by betatim** [comment]
Maybe to sweeten the deal on moving to sphinx: there is work on going to connect binder to your standard sphinx based documentation page. So people can run snippets.

**Comment by chschroeder** [comment]
Is this still on the schedule? And if so, do you need any help here?

**Comment by betatim** [comment]
Yes and yes. I still think switching to sphinx would be a win. Not sure if it would be easier to rebase this PR or start from scratch to get a consistent formatting in our docstrings.

Maybe cherry-picking the sphinx setup stuff, and then formatting doc strings from scratch.

I also did a bit of digging to see if there is a tool that could help us automate the conversion and found: https://bitbucket.org/RobRuana/sphinx-contrib/src/a311ef7908cb/napoleon Not sure it is exactly what we need, so just leaving it here for the moment.

**Comment by chschroeder** [comment]
Great :+1: I would also have some other things to work on, relating to the ask and tell API, but i think the docs are the more important right now (and will become harder to migrate, the longer we wait).

> Maybe cherry-picking the sphinx setup stuff, and then formatting doc strings from scratch.

Sounds reasonable to me.

How should we organize this? Start at `betatim:sphinxing` and i make PRs against that branch?

**Comment by betatim** [comment]
> How should we organize this? Start at `betatim:sphinxing` and i make PRs against that branch?

👍, sounds like a plan to me!

**Comment by chschroeder** [comment]
Sorry, i will probably not start this until the end of next week. So just ignore it until then. I don't want to make you wait.

**Comment by betatim** [comment]
Ok, so I also had no time to work on this. Right now I am thinking just start a new PR, cherry picking what you need from this PR. That is probably more efficient. We can also have several small PRs that add stuff "behind the scenes" so we can build up to it instead of having to have one huge PR. Basically we only switch over to the new doc building method once we are happy and keep the old one running while we work in the background.

**Comment by chschroeder** [comment]
I'm back :tada:. PR coming soon (still some things unclear). You mentioned the napoleon plugin, does this mean that we keep the numpy docstring style?

I will probably write an issue that covers the big picture (so that we can focus on multiple small PRs).

**Comment by betatim** [comment]
The numpy doc style (or more specifically the style used in scikit-learn) would be my preferred option. IMHO it is "the best" compromise between verbosity, weird syntax, etc, if you have strong feelings make them known and we can discuss them.

**Comment by chschroeder** [comment]
Not at all, this is perfectly fine with me :). I just noticed i had an incomplete understanding of what the desired outcome is.

**Comment by chschroeder** [comment]
Just opened the issue and the first PR (WIP). Let's move the discussion to #640.

**Comment by holgern** [comment]
Sphinx migration will continue in PR #811

**Pull request closed without merging**
