### PR TITLE
setup.py now reflects that skopt needs sklearn that has MaskedArray in its fixes.py

### PR DESCRIPTION
**Pull request by pavelkomarov**
This is my first pull request to you and my first contribution to anything open source where I don't know the owners personally. It's mostly to familiarize myself with the fact I have to fork the repo and push to a branch I own (because permissions) and other minutiae, but it also solves #569 by letting potential users know they can't use scikit-learn 0.18.0. Hopefully more substantial changes to come, since I've opened several issues I don't expect anyone else will fix for me.

### CODE REVIEW

**Comment by betatim** [comment]
LGTM. Little PRs like this are win-win: you get to test drive the contribution process, we get small issues fixed :)

Welcome aboard as contributor and also congratulations to having an employer that supports working on open-source during office hours!

**Comment by betatim** [comment]
Two small process comments:

* can you add a [WIP] (work in progress) or [MRG] (ready for review and merge) tag at the start of the title? This is being documented in #596.
* if your PR fixes/closes an issue then you can mention (on a line by itself??) the issue like "Fixes #XXX" which GitHub recognises and then auto closes the issue when the PR gets merged. Helps us with bookkeeping

**Comment by betatim** [comment]
A heads up: I tried visiting http://www.northropgrumman.com but only get "The connection was reset" errors.

**Comment by pavelkomarov** [comment]
I can connect. Maybe they have some odd block for those out of country?

Yes, I can adapt my process in those ways.

My employer isn't directly supporting this, but at a certain hour of the night, if I've gotten other work done, I'm basically unsupervised and free to do anything I think will help me and us. Since my current work depends so heavily on skopt, it's worth work time.

**Comment by betatim** [comment]
Ah ok, I assumed they were paying you to work on this because you added them to the README :)

**Pull request merged**
