### PR TITLE
[MRG] Time tests and report coverage

### PR DESCRIPTION
**Pull request by betatim**
This prints a list of the slowest tests and uploads the coverage (from py3.5) to codecov so we can actually look at it.

To see if we can speed up the tests we need to see what is slow, otherwise we will never think about it. As we already collect the coverage info it also makes sense to put it somewhere so we can see it -> we might start improving coverage.

* [x] exclude `skopt/tests/` from codecov report

### CODE REVIEW

**Comment by MechCoder** [comment]
Yes, this will be highly useful. But where can we see the output? In the travis log?

**Comment by betatim** [comment]
A summary of the coverage will be posted in the PR as a comment. The timing will be in the travis log.

**Comment by betatim** [comment]
Bam! 87% coverage, not bad considering we never explicitly checked it!

**Comment by MechCoder** [comment]
Awesome, thanks!

**Comment by betatim** [comment]
I sneaked in a minor modification with  336f762

**Pull request merged**
