### PR TITLE
[MRG] Execute notebooks after each deploy

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by MechCoder** [comment]
cc: @betatim @glouppe ;)

**Comment by glouppe** [comment]
Yup, looks like the solution was simple in the end :-) 

Do you know if we have time constraints on Travis? Running the notebooks might take long. 

If not, then +1 for merge.

**Comment by MechCoder** [comment]
There is a timeout for tests which is 50 minutes. Not sure if it applies for `after_success` also.

**Comment by glouppe** [comment]
Okay, well, let's merge and see by ourselves see if Travis dies of sudden death :skull:

**Comment by glouppe** [comment]
Hmm, this still requires some tuning https://travis-ci.org/scikit-optimize/scikit-optimize/jobs/149973693#L520

**Comment by betatim** [comment]
Nice!

**Pull request merged**
