### PR TITLE
Use joblib instead of sklearn.externals.joblib

### PR DESCRIPTION
**Pull request by vakker**
Fixing `DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.`

Should resolve [#774](https://github.com/scikit-optimize/scikit-optimize/issues/774)

### CODE REVIEW

**Comment by kitchoi** [comment]
The test failures look unrelated (#777 may fix those).
Probably need to add `joblib` to the requirements as well?:
https://github.com/scikit-optimize/scikit-optimize/blob/6740876a6f9ad92c732d394e8534a5236a8d3f84/setup.py#L18-L19

**Comment by vakker** [comment]
@kitchoi thanks, that did solve 1 build error, but there's still a few more that doesn't seem to be related to this PR.
They are all related to `fit_params` being removed and maybe the tests weren't updated:
```
        super(BayesSearchCV, self).__init__(
             estimator=estimator, scoring=scoring, fit_params=fit_params,
             n_jobs=n_jobs, iid=iid, refit=refit, cv=cv, verbose=verbose,
             pre_dispatch=pre_dispatch, error_score=error_score,
>            return_train_score=return_train_score)
E       TypeError: __init__() got an unexpected keyword argument 'fit_params'
```

**Comment by vakker** [comment]
I believe it's actually [#762](https://github.com/scikit-optimize/scikit-optimize/issues/762), that's causing it.

**Comment by kitchoi** [comment]
> I believe it's actually #762, that's causing it.

Yes #777 should close it.  CI on #777 is green, so I am hoping if #777 gets merged, then you can merge master to here in order to get a clean build.

**Comment by holgern** [comment]
@betatim or @glouppe please merge also this PR, it will fix issue #774

**Pull request merged**
