### PR TITLE
Bump version to 0.4

### PR DESCRIPTION
**Pull request by betatim**
Preparation for releasing v0.4. Once this get's merge I'll tag the new version and we should have a new release.

What about #465? I think the test I added should pass? Should we wait for that PR?

### CODE REVIEW

**Comment by betatim** [comment]
What did I forget to do for the release?

**Comment by iaroslav-ai** [comment]
#465 would be awesome to add if you think it can be added soon - but I think not critical.

**Comment by betatim** [comment]
If this builds I will tag 0.4rc1, see if the "push directly to PyPI" setup works, if yes then tag 0.4 straight away unless we find some weird last minute bugs.

**Comment by iaroslav-ai** [comment]
Awesome! :D

**Pull request merged**
