### PR TITLE
[MRG+1] Refactor initialization of Optimizer and improve readability of comments of base optimizer

### PR DESCRIPTION
**Pull request by kejiashi**
The initialization of the optimizer class has a function `_check_argument`. I don't know if this has other usage to be separated. So I try to refactor the argument configuration process.

I also edited some comments in base file to improve the readability.

### CODE REVIEW

**Comment by kejiashi** [comment]
Got your points. Will add the blank line.

Apart from checking random state, there are four parts related to optimization (acquisition function, estimator, optimizer, search space) that need to be configured, along with necessary assignment of storage for results and point counters.

Would separating these four parts into individual functions be preferable? Say, `_configure_acq_func`, `_configure_estimator`, `_configure_optimizer`, `_configure_space`. Or there're too many functions in the optimizer?

**Comment by iaroslav-ai** [comment]
Hi @kejiashi , thanks for this PR! 
The benefit of putting everything in functions would be improved readability of "top" method. But then there is more depth to the code, so I am personally not sure what is best. 
(I add MRG to the title, but feel free to change it).

**Comment by kejiashi** [comment]
Thank you for your reply, @iaroslav-ai . I feel the same. There are already 9 functions inside the `Optimizer` class. On the other hand, the initialization has almost the same length as the `tell` function. (~110 lines)

Just added back the line separates. But I have no idea why it breaks CircleCI at `ask-and-tell.ipynb` this time.

**Comment by iaroslav-ai** [comment]
Not sure why circleci failed. I restart it.

**Comment by iaroslav-ai** [comment]
Humm it seems I do not have permissions to run circleci again.

I am not sure also what the error there is all about. It is something related to notebooks it seems

**Comment by iaroslav-ai** [comment]
Just ran the notebook conversion on my machine, all works.

**Comment by iaroslav-ai** [comment]
If someone with access can rerun the circleci that would be great. Otherwise I merge this tomorrow - seems some circleci specific issue.

**Comment by iaroslav-ai** [comment]
After some digging into circleci issue it appears to be some jupyter specific issue, and not related to the PR: 

https://github.com/jupyter/jupyter_client/issues/154

Thus I merge. 
Thank you @kejiashi ! :+1: :tada:

**Comment by kejiashi** [comment]
Thanks!

**Pull request merged**
