### PR TITLE
Return type should be a list of lists

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by glouppe** [comment]
Thanks for this! +1 modulo Travis' veto

**Comment by MechCoder** [comment]
We should probably refactor most of the tests in `tests_common.py` similar to sklearn's. But among other things, refactoring is not my idea of fun :p

**Comment by glouppe** [comment]
Sure, we can do that later though.

**Comment by betatim** [comment]
@MechCoder you should join me for the party over in #139 🎉

**Pull request merged**
