### PR TITLE
[MRG] make the BO notebook great again

### LINKED ISSUE #277: The BO notebook still fails
https://scikit-optimize.github.io/notebooks/bayesian-optimization.html

CC: @MechCoder 

Again, I think we should fix `n_restarts_optimizer` in `GaussianProcessRegressor` to a larger value once and for all.

### PR DESCRIPTION
**Pull request by glouppe**
This fixes #277. I simplified a few things and made the plots work again.

### CODE REVIEW

**Comment by betatim** [comment]
What happened to circle CI? Wanted to look at the prerendered notebook but circle CI didn't run??

**Comment by glouppe** [comment]
No idea :o

(sent from my phone)

**Comment by glouppe** [comment]
The notebook should look like this https://github.com/glouppe/scikit-optimize/blob/18b93c770717977fee0602654be6c2e25ede6a63/examples/bayesian-optimization.ipynb

**Comment by betatim** [comment]
concours - > contours (last plot)

**Comment by glouppe** [comment]
I fixed the typo. Merge?

**Comment by betatim** [comment]
I'll wait for travis, then merge. How do we fix circle CI?

**Comment by betatim** [comment]
:clinking_glasses:

**Comment by MechCoder** [comment]
Something to do with the timeout increase in https://github.com/scikit-optimize/scikit-optimize/commit/3f67b86269b6f5c29609248c921bd25d6b358b61? That seems to be the most recent change.

**Pull request merged**
