### PR TITLE
[MRG] Update number of random points to be sampled to optimize the acquisition function.

### PR DESCRIPTION
**Pull request by MechCoder**
Here we go (on hart6):

Before:
index

hart6

### CODE REVIEW

**Comment by MechCoder** [comment]
Tests fail. This is non-intuitive to me :(

**Comment by glouppe** [comment]
Maybe we can slightly adjust the allowed margin error of those tests? 

But the main reason i think is that optimization gets stucked in a local minima and never escapes from it because of a lack of exploration (which is partly due to how the returned std behaves in regions that have not been seen by the forest).

**Comment by MechCoder** [comment]
I'll have a look at the tests tomorrow.

**Comment by glouppe** [comment]
Set to `n_points=1000` as part of #174. Closing.

**Pull request closed without merging**
