### PR TITLE
Deploy notebooks with the static documentation

### PR DESCRIPTION
**Pull request by glouppe**
I am merging this right now, as I need to check whether Travis deploys correctly. We will improve things afterwards.

### CODE REVIEW

**Comment by betatim** [comment]
💯

**Comment by glouppe** [comment]
Travis seems to have internal issues, jobs are queuing...

**Comment by glouppe** [comment]
https://scikit-optimize.github.io/notebooks/Bayesian%20optimisation.html !

The architecture is properly setup, now the next thing is to write a nice notebook describing Bayesian optimisation and our API :)

**Comment by glouppe** [comment]
Note that the notebook I shipped was only for test purposes. It is mostly copy/pasted from one of our examples. It should really be improved with narrative documentation, better figures, etc.

**Comment by betatim** [comment]
Is there a way to specify/automagic a nicer URL? Or we just agree to use "nice" file names for the notebooks so the URLs are nice too.

This is super cool. /me dreams of interactive docs ... one day :)

**Comment by glouppe** [comment]
A better solution could certainly be hacked than what I do for the moment. E.g., by renaming the notebook files once they have been rendered (hence using the original nice name for the link text, and the renamed version for the url).

**Comment by MechCoder** [comment]
This looks great!

**Comment by glouppe** [comment]
Just pushed a1fbee21fcd1d4b1eeb390e1afe4657ff878a70f

URLs should now be better (once Travis has finished redeploying the doc)

**Comment by glouppe** [comment]
https://scikit-optimize.github.io/notebooks/bayesian-optimisation.html  does this url look better? :)

**Comment by MechCoder** [comment]
great, thanks!

**Comment by betatim** [comment]
Oh yeah!

**Pull request merged**
