### PR TITLE
[MRG] Example for `plot_evaluations` and `plot_objective`

### PR DESCRIPTION
**Pull request by betatim**
An example on how to use `plot_evaluations()` and how to read its output.

Related to #162

### CODE REVIEW

**Comment by betatim** [comment]
This also fixes up a mistake in the layout of the 2D plot matrix with the position of the `x` label of the on-diagonal plots and chooses the figure size based on the number of dimensions. (could refactor this into a separate PR if you want)

**Comment by glouppe** [comment]
Will you also combine this notebook with explanations for `plot_objective`?

**Comment by betatim** [comment]
Yes, `plot_objective` in the the same notebook is the plan (but my train arrived :)). This also still needs some tuning in terms of being a good example.

**Comment by glouppe** [comment]
These functions are really great! Love the notebook so far. Ping us once you want reviews :)

**Comment by glouppe** [comment]
Some comments as I read along:

- visualizing-samples.ipynb -> visualizing-results ?
- Visualizing the objective function -> Visualizing optimization results?
- objecitves  -> objectives
- in the intro, maybe recall that the `*_minimize` all return a dict-like object which can inspected. The `plot_*` functions are helpers designed for that purpose. 
-  is it necessary to redefine `branin` and `hart` with an optional noise level if this later argument is not used afterwards? 
-  might be helpful to remind readers what is a partial dependence plot ;)

**Comment by betatim** [comment]
Used my super powers to edit your comment adding checkboxes.

`hart6` is still redefined but without noise so that I can add "noisy" dimensions.

Working on a explanation of partial dependence.

**Comment by betatim** [comment]
All done.

**Comment by glouppe** [comment]
This is really cool! +1 for me, we can still brush things later

**Comment by betatim** [comment]
Merging! 💚

**Pull request merged**
