### PR TITLE
[MRG] Log time in VerboseCallback and return callbacks in OptimizeResult instance

### PR DESCRIPTION
**Pull request by MechCoder**
- [x] Introduce attribute `total_time` in `VerboseCallback`
- [x] Allow `return_callbacks` argument that sets the attribute callbacks in the returned `OptimizeResult` instance.

### CODE REVIEW

**Comment by MechCoder** [comment]
Is it useful to split the time taken for function evaluation and the time taken to fit the surrogate model? In some cases, it is useful when the time taken for a function evaluation completely varies (for example, while tuning regularization etc.)

Not sure how to do it with the current API though.

**Comment by betatim** [comment]
Do we really need the `return_callbacks` argument? I'm not in love. My vote would be to always attach the info from the callbacks (if they provide any).

Should we attach the callbacks themselves or have a way of specifying which bit of info from the callbacks to add to the result? Not sure how easy that is to do technically but from a user perspective it would be much nicer to have `res.info.total_time` (maybe change `info` to another name). So we store additional info computed by the callbacks in the `info` attribute.

**Comment by MechCoder** [comment]
Sounds reasonable. How about just `res.iter_time` instead of `res.total_time`?

**Comment by betatim** [comment]
Think we should prefix it with something `res.name_of_callback.blah`?? The attribute should be named the same as the attribute from the callback.

How would you automatically pick which attributes of a callback to store? Should we adopt the convention that `self.attribute_` is stored but `self.otherattr` isn't? Or add a method to the callbacks to return "the summary to be attached" to each callback object?

**Comment by glouppe** [comment]
> My vote would be to always attach the info from the callbacks (if they provide any).

+1

**Comment by MechCoder** [comment]
I'm fine with just doing `res.name_of_the_callback.blah` with all the (public) attributes from the callback instance. Is that the consensus?

**Comment by glouppe** [comment]
You cannot know the name of the callback in advance, since these may be user supplied. Just fill the list `res.callbacks`.

**Comment by MechCoder** [comment]
Well, you can always do `callback.__class__.__name__` and such stuff. Taking a step back, what advantage does the user have in the optimization procedure returning all the callbacks? (I know I wrote it, but still)

**Comment by glouppe** [comment]
I dont know. What was the use case you had in mind? why do you need to keep track of them? I am +0 for returning callbacks at all.

**Comment by MechCoder** [comment]
I just wanted to get the time for every iteration.

**Comment by MechCoder** [comment]
(Not the first time I've over - engineered something). I would be okay with just storing a `iter_time` attribute on the OptimizeResult instance if verbose is set to be True.

**Comment by glouppe** [comment]
I am not convinced by adding anything at all to `OptimizeResult`. If you want to inspect attributes from a callback, then inspect that callback, not some other object.

**Comment by MechCoder** [comment]
See https://github.com/scikit-optimize/scikit-optimize/pull/216

**Pull request closed without merging**
