### PR TITLE
[MRG] Add "made possible by" section to README

### PR DESCRIPTION
**Pull request by betatim**
What do you think about this?

Can/should we list NYU and Saarland University?

### CODE REVIEW

**Comment by glouppe** [comment]
+1 for NYU Center for Data Science, it covered my expenses and Manoj's for some time.

cc: @cranmer

**Comment by betatim** [comment]
[is the twitter bio picture](https://twitter.com/nyudatascience) the preferred logo? If someone points me at it I will incorporate it.

**Comment by iaroslav-ai** [comment]
I think it is fine to mention Saarland University, but I did not officially announced to anyone there that I am working on this software. Furthermore, I officially do not work for Saarland Unviersity for some time, but for a different employer :) So I will need to check with some people if it is ok (just in case there are some policies that I did not expect). If I am inactive on this, just go on without Saarland University, and we can add it later.

**Comment by betatim** [comment]
@glouppe can you give a 👍  or 👎  on the NYU logo? We can always update it when we get "official" advice. I propose we add NYU and leave Saarland (and @iaroslav-ai's new mystery employer) out for the moment.

**Comment by cranmer** [comment]
The NYU CDS logo is fine.

The. NSF was primarily supporting @glouppe during that time
https://www.nsf.gov/policies/logos.jsp

**Comment by betatim** [comment]
Added NSF and NYU. Ready to merge.

**Comment by glouppe** [comment]
Merging :)

**Pull request merged**
