### PR TITLE
cluttered around the minimum -> clustered around the minimum

### PR DESCRIPTION
**Pull request by andreh7**
'clutter' is actually a synonym of 'litter'

### CODE REVIEW

**Comment by betatim** [comment]
Thanks for this! Will have to find a minute later today to investigate how to get circleCI to rerun the test. Seems like it just timed out because running the examples took too long.

**Comment by andreh7** [comment]
In principle, this is just a one letter change so it would be easy for you to do the modification yourself. But I guess the problem with circleCI timing out is worth solving anyway because it might affect more than just this pull request...

**Comment by betatim** [comment]
As a rule we only merge things if travis and circle are green, independent of who proposes the change 😄. As you said, fixing the CircleCI timeout now is going to be worth it in the long term.

Thanks for your patience and also for making the effort of creating a PR for a small change!

**Comment by glouppe** [comment]
All checks are now passing. Thanks @andreh7 !

**Comment by betatim** [comment]
The magic of "retry build" :)

**Pull request merged**
