### PR TITLE
[WIP] Fix passing on the verbose flag in GBRT

### LINKED ISSUE #326: gbrt_minimize, verbose=True not working
Hi,

I am trying to use gbrt_minimize with verbose=True, but it's not printing anything to the screen. forest_minimize works fine.

Thanks,

Mario

### PR DESCRIPTION
**Pull request by betatim**
Fixes #326 

What would be a good way to test for output when the verbose flag is set in a test (without having to resort to replacing `sys.stdout` myself)?

### CODE REVIEW

**Comment by betatim** [comment]
From some googling it seems that in nosetest there is no other way than to replace `sys.stdout` with a `BytesIO`. Which is simple enough but starts to get annoying if you want to run the test in pdb.

**Comment by MechCoder** [comment]
lgmt

**Comment by betatim** [comment]
I'd like to add a test for this before we merge (unless there is a need to merge quickly in which case we can punt the test to a new issue).

**Comment by glouppe** [comment]
I am happy with merging this now.

**Comment by betatim** [comment]
Done.

**Pull request merged**
