### PR TITLE
[MRG] PR #675

### PR DESCRIPTION
**Pull request by holgern**
Evaluate and merge PR #675 with upstream

### CODE REVIEW

**Comment by holgern** [comment]
This PR is ready to be merged. @betatim or @glouppe can you have a look and merge if everything looks good?
Thanks.

**Comment by glouppe** [comment]
I am wondering if converting a categorical into a real value is really the right thing to do for plots. It is certainly better than nothing, and I wouldn't disagree in merging this, but maybe should make it good from the start?

For plots mixing categorical and continuous axis, there are good suggestions at:
- https://seaborn.pydata.org/tutorial/categorical.html
- http://www.cs.umd.edu/hcil/trs/2016-10/2016-10.pdf

I'd rather have a second opinion before merging this one. @betatim?

**Comment by holgern** [comment]
I think this PR is a first starting point and it will be possible to improve plots with categorical data based on the introduced changes.

**Comment by glouppe** [comment]
@betatim what do you think?

**Comment by glouppe** [comment]
I am merging this for now. Thanks Holger!

**Pull request merged**
