### PR TITLE
[MRG] Bump version numbers and dependency on sklearn

### PR DESCRIPTION
**Pull request by iaroslav-ai**
Related to release of v0.5
#578

### CODE REVIEW

**Comment by betatim** [comment]
Should we close #608 in favour of this one? #seeingdouble

**Comment by iaroslav-ai** [comment]
Good idea

**Comment by betatim** [comment]
(We get two travis builds if you push your branches to this repo. I think we should stick to having our branches in our repos and keeping this one "clean". Reduces travis hassle and chances of accidentally screwing things up with git-foo)

**Comment by iaroslav-ai** [comment]
:+1:

**Comment by iaroslav-ai** [comment]
Merging this - will revert if anyone has any comments on this

**Pull request merged**
