### PR TITLE
Yet more pinning of QT versions

### PR DESCRIPTION
**Pull request by betatim**
See ContinuumIO/anaconda-issues#1090

This PR will also need undoing as part of #230

### CODE REVIEW

**Comment by MechCoder** [comment]
We pip install from sklearn master, right? Any idea why it searches for `sklearn-0.18 dev`?

**Comment by betatim** [comment]
Potentially because of the #sklearn-0.18dev in the URL (I think). I am a bit frustrated with conda atm. Looks like we need to pin to different builds for py27 and py3, so this is getting pretty tedious.

Was wondering if we could just use `pip` for everything instead? Seems like there are `manylinux` wheels for lots of packages these days.

**Comment by MechCoder** [comment]
I restarted the build on master and it seemed to pass

**Comment by betatim** [comment]
Looks like ContinuumIO/anaconda-issues#1090 is fixed which should make most of this obsolete and in ContinuumIO/anaconda-issues#1068 I see a lot of people unpinning QT as well. So maybe that is fixed as well. Closing this.

**Pull request closed without merging**
