### PR TITLE
Add __init__.py to tests folders

### PR DESCRIPTION
**Pull request by lesteve**
I expect to be able to run the tests in the top-level folder without having to install the package (long story short I never install dev packages in my environment). In master I get 

<details>
<summary>Test errors</summary>

```
================================================ test session starts ================================================
platform linux -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/le243287/dev/scikit-optimize, inifile:
collected 0 items / 16 errors 

====================================================== ERRORS =======================================================
________________________ ERROR collecting skopt/learning/gaussian_process/tests/test_gpr.py _________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/learning/gaussian_process/tests/test_gpr.py'.                                                                                                           
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/learning/gaussian_process/tests/test_gpr.py:12: in <module>                                                    
    from skopt.learning import GaussianProcessRegressor                                                              
E   ModuleNotFoundError: No module named 'skopt'                                                                     
______________________ ERROR collecting skopt/learning/gaussian_process/tests/test_kernels.py _______________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/learning/gaussian_process/tests/test_kernels.py'.                                                                                                       
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/learning/gaussian_process/tests/test_kernels.py:10: in <module>                                                
    from skopt.learning.gaussian_process import GaussianProcessRegressor                                             
E   ModuleNotFoundError: No module named 'skopt'                                                                     
________________________________ ERROR collecting skopt/learning/tests/test_gbrt.py _________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/learning/tests/test_gbrt.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/learning/tests/test_gbrt.py:14: in <module>                                                                    
    from skopt.learning import GradientBoostingQuantileRegressor                                                     
E   ModuleNotFoundError: No module named 'skopt'                                                                     
_________________________________ ERROR collecting skopt/tests/test_acquisition.py __________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_acquisition.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_acquisition.py:13: in <module>                                                                      
    from skopt.acquisition import _gaussian_acquisition                                                              
E   ModuleNotFoundError: No module named 'skopt'                                                                     
__________________________________ ERROR collecting skopt/tests/test_benchmarks.py __________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_benchmarks.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_benchmarks.py:7: in <module>                                                                        
    from skopt.benchmarks import branin                                                                              
E   ModuleNotFoundError: No module named 'skopt'                                                                     
__________________________________ ERROR collecting skopt/tests/test_callbacks.py ___________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_callbacks.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_callbacks.py:9: in <module>                                                                         
    from skopt import dummy_minimize                                                                                 
E   ModuleNotFoundError: No module named 'skopt'                                                                     
____________________________________ ERROR collecting skopt/tests/test_common.py ____________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_common.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_common.py:18: in <module>                                                                           
    from skopt import dummy_minimize                                                                                 
E   ModuleNotFoundError: No module named 'skopt'                                                                     
_________________________________ ERROR collecting skopt/tests/test_deprecation.py __________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_deprecation.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_deprecation.py:6: in <module>                                                                       
    from skopt import gp_minimize                                                                                    
E   ModuleNotFoundError: No module named 'skopt'                                                                     
__________________________________ ERROR collecting skopt/tests/test_dummy_opt.py ___________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_dummy_opt.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:                                                                                                           
skopt/tests/test_dummy_opt.py:5: in <module>                                                                         
    from skopt import dummy_minimize                                                                                 
E   ModuleNotFoundError: No module named 'skopt'                                                                     
__________________________________ ERROR collecting skopt/tests/test_forest_opt.py __________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_forest_opt.py'.
Hint: make sure your test modules/packages have valid Python names.                                                  
Traceback:
skopt/tests/test_forest_opt.py:8: in <module>
    from skopt import gbrt_minimize
E   ModuleNotFoundError: No module named 'skopt'
____________________________________ ERROR collecting skopt/tests/test_gp_opt.py ____________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_gp_opt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_gp_opt.py:7: in <module>
    from skopt import gp_minimize
E   ModuleNotFoundError: No module named 'skopt'
__________________________________ ERROR collecting skopt/tests/test_optimizer.py ___________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_optimizer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_optimizer.py:9: in <module>
    from skopt.benchmarks import bench1
E   ModuleNotFoundError: No module named 'skopt'
_________________________________ ERROR collecting skopt/tests/test_parallel_cl.py __________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_parallel_cl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_parallel_cl.py:9: in <module>
    from skopt.space import Real
E   ModuleNotFoundError: No module named 'skopt'
___________________________________ ERROR collecting skopt/tests/test_searchcv.py ___________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_searchcv.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_searchcv.py:13: in <module>
    from skopt.space import Real, Categorical, Integer
E   ModuleNotFoundError: No module named 'skopt'
____________________________________ ERROR collecting skopt/tests/test_space.py _____________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_space.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_space.py:15: in <module>
    from skopt.space import Space
E   ModuleNotFoundError: No module named 'skopt'
____________________________________ ERROR collecting skopt/tests/test_utils.py _____________________________________
ImportError while importing test module '/home/le243287/dev/scikit-optimize/skopt/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
skopt/tests/test_utils.py:8: in <module>
    from skopt import gp_minimize
E   ModuleNotFoundError: No module named 'skopt'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 16 error in 1.59 seconds ==============================================

```
</details>

This PR allows to run the tests with `pytest skopt`. It just adds `__init__.py` to `tests` folders.

Also I think in general this is good practice to have `tests` folders to be subpackages. This is certainly what I have encountered in most packages I worked on so far. I seem to remember it may simplify `setup.py` a bit.

### CODE REVIEW

**Comment by betatim** [comment]
Do you know why making the tests into modules fixes the problem of importing the `skopt` module? From the error message it makes me think there is a problem finding the module.

For my curiosity can you run `pytest` from the top level directory in the case with and without `__init__.py` files to see how/if the error changes?

**Comment by glouppe** [comment]
LGTM.

**Comment by lesteve** [comment]
> Do you know why making the tests into modules fixes the problem of importing the skopt module? From the error message it makes me think there is a problem finding the module.

Not really, I would guess this is related to smart sys.path handling that pytest uses (see https://docs.pytest.org/en/latest/pythonpath.html#test-modules-conftest-py-files-inside-packages for more details). pytest recommends a few different approaches for the test folders layout and I think the one I am used to (numpy, scipy, scikit-learn, pandas, joblib, etc ...) is: https://docs.pytest.org/en/latest/goodpractices.html#tests-as-part-of-application-code. There you can see that tests folders have `__init__.py`.

Note you can do `PYTHONPATH=. pytest skopt` to work-around the problem. As someone that is quite familiar with these things it took me some time to figure it out so I can imagine a random contributor to be really puzzled by this.

> For my curiosity can you run pytest from the top level directory in the case with and without __init__.py files to see how/if the error changes?

I am not exactly sure what you are asking here. It seems to me that "with" is what this PR does and "without" is what master does.

**Comment by betatim** [comment]
Thanks for the lesson and the fix. If the pytest gurus recommend it then we should just do it :)

**Comment by lesteve** [comment]
Great!

**Pull request merged**
