### PR TITLE
[MRG] Add notebooks to sphinx doc

### PR DESCRIPTION
**Pull request by holgern**
image

* New theme taken from scikit-learn
* Improved sphinx-doc structure
* Use of sphinx-gallery to generate notebooks
* New docu will be available at https://scikit-optimize.github.io/beta

Advantages of sphinx-gallery are
* Output of examples is up to date
* Python script and notebook is available
* Examples can be run in binder
* Linking with help files is possible

When everything works, I will create a new PR and remove all ipynb files and the make_doc generation script

PRs #641 and #431 can be closed when this PR is merged.

### CODE REVIEW

**Comment by holgern** [comment]
Hello @betatim and @glouppe ,
this PR is ready for merging. It will not break the old github documentation and will create the new version at https://scikit-optimize.github.io/beta

We can then remove the old documentation in the next PR, when everything looks good.

**Comment by glouppe** [comment]
Thanks Holger! This is really really nice!

Shouldn't we however have our own color palette, to avoid confusion with Scikit-Learn?

**Comment by holgern** [comment]
That is a good idea, do you have something in mind?

**Comment by holgern** [comment]
I changed the colors:
image

and used mainly:
#d98880
#80d988
#8880d9

**Comment by holgern** [comment]
[html.zip](https://github.com/scikit-optimize/scikit-optimize/files/4122623/html.zip)
Current sphinx help with examples

**Comment by glouppe** [comment]
This is quite subjective, but I dont find this new color palette very pretty :x I would stick to two colors (possibly with white as intermediate in the gradient).

**Comment by holgern** [comment]
image
[html.zip](https://github.com/scikit-optimize/scikit-optimize/files/4122755/html.zip)

Second try, I think it is now better.

**Pull request merged**
