### PR TITLE
[MRG] Add sphinx doc without breaking the current doc site

### PR DESCRIPTION
**Pull request by holgern**
This adds a sphinx doc to scikit-optimize without breaking the current doc generation.

### CODE REVIEW

**Comment by holgern** [comment]
@betatim or @glouppe can you merge this PR? It adds the option to create a sphinx documentation without breaking the existing github site.

The sphinx doc will be available at https://scikit-optimize.github.io/rtd and we can decide later if we replace the current  site or just add a link to the new sphinx doc.

**Comment by glouppe** [comment]
Good with me, as a test.

Do you think it could also play well with the notebooks?

**Comment by holgern** [comment]
I will try to add the notebooks on a new PR
The sphinx doc can be found here:
https://scikit-optimize.readthedocs.io/en/latest/index.html

**Comment by glouppe** [comment]
Thanks! This looks quite nice :)

**Pull request merged**
