### PR TITLE
[MRG] Improve hyperparameter optimisation objective notebook

### PR DESCRIPTION
**Pull request by MechCoder**
Fixes https://github.com/scikit-optimize/scikit-optimize/issues/254

### CODE REVIEW

**Comment by betatim** [comment]
Ready to be reviewed?

**Comment by MechCoder** [comment]
yeas:D

**Comment by betatim** [comment]
Do we need the "Introduction" headline at the start of the pipeline example?

Other than that I am fine.

**Comment by MechCoder** [comment]
Fixed, will merge when tests pass.

**Pull request merged**
