### PR TITLE
[MRG] remove forest_minimize(base_estimator="dt")

### LINKED ISSUE #188: Remove forest_minimize(base_estimator=dt)?
` forest_minimize(base_estimator=dt)` is expected to perform poorly almost always. I would be in favor of removing it before the release, to avoid users shooting themselves in the foot. 

(For the power user, an exact equivalent can still be retrieved by passing `base_estimator=RandomForestRegressor(n_estimators=1, max_feature=1.0, bootstrap=False)`).

### PR DESCRIPTION
**Pull request by glouppe**
Fixes #188

### CODE REVIEW

**Comment by MechCoder** [comment]
lgtm

**Comment by betatim** [comment]
Great to see code being removed ♻️. LGTM

**Comment by glouppe** [comment]
Thanks! I'll merge if I get the green light from Travis

**Comment by MechCoder** [comment]
Maybe rename `tree_opt` to `forest_opt`?

**Pull request merged**
