### PR TITLE
List packages for setup.py

### LINKED ISSUE #152: Setup.py install does not work
Not sure why, but locally `python setup.py install` never seems to work. The `skopt` module can never found afterwards. By contrast  `python setup.py develop` does work.

Can anybody try to reproduce this in some test env?

### PR DESCRIPTION
**Pull request by betatim**
Fixes #152 

Added a few more fields as well. Who is the author of skopt? What about "The scikit-optimize contributors"? Should we make an email address (what doe sklearn do for this?)?

### CODE REVIEW

**Comment by betatim** [comment]
Explicitly listing the packages like this means we avoid having to deal with `find_packages` not being available in `distutils`. If one day we have lots of packages and get bored of listing them we can switch.

**Comment by glouppe** [comment]
> What about "The scikit-optimize contributors"?

+1

**Comment by glouppe** [comment]
and +1 for this

**Comment by betatim** [comment]
I'll merge once travis is happy.

**Pull request merged**
