### PR TITLE
Fixup examples to use new parameter names

### LINKED ISSUE #135: gp_example len() of unsized object
This

scikit-optimize/examples/plot_gp_minimize_1d.py

throws an error:

Traceback (most recent call last):
  File "gp_example.py", line 57, in <module>
    plt.fill_between(x, -1.5, acquis_values, alpha=0.3, color='green', label="LCB values")
  File "/Users/kegl/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2826, in fill_between
    interpolate=interpolate, **kwargs)
  File "/Users/kegl/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4340, in fill_between
    where = np.ones(len(x), np.bool)
TypeError: len() of unsized object

### PR DESCRIPTION
**Pull request by betatim**
Catching up the examples to the new API.

Looked into this to fix #135 but can't reproduce that bug.

This makes me think we should run these on travis. Otherwise they will keep being out of date :-/

### CODE REVIEW

**Comment by glouppe** [comment]
We should just remove them, eventually.

**Comment by betatim** [comment]
Or move them to notebooks. We will have the same problem with the notebooks though :-/

**Comment by MechCoder** [comment]
merging!

**Comment by betatim** [comment]
⚡

**Pull request merged**
