### PR TITLE
[MRG] Changing options for base_estimator to uppercase

### PR DESCRIPTION
**Pull request by jtsmith2**
This is a fix for issue #153 to change the arguments to the base_estimator parameter of the forest_minimize function to uppercase.  I made edits in the forest.py and test_forest_opt.py files to reflect the changes.

This is my first contribution so I'm open to feedback on any mistakes I'm making.  (Blame @betatim and Linear Digressions for bringing me here :smile:)

### CODE REVIEW

**Comment by betatim** [comment]
Welcome! To answer your question from the issue: changing the arguments to upper case is what was meant. This makes it more consistent with other string arguments we have like `'LCB'` and such. Personally I would be against making the arguments case insensitive (your option 2).

There is a few tests that fail as they use the (now) old convention.

**Comment by jtsmith2** [comment]
Thanks.  Travis caught a test I missed (test_common) and so I made an update there.  I'm a bit unsure of what circleci is telling me.

**Comment by betatim** [comment]
CircleCI executes the notebooks stored in [`examples/`](https://github.com/scikit-optimize/scikit-optimize/tree/master/examples) and does other work to render our webpage. What it is trying to tell you (in its slightly special way) is that the examples use the old kind of argument capitalization. Download the build log from the "$ bash ./build_tools/circle/install.sh" step to see the error message.

**Comment by betatim** [comment]
Nice!

It would be good to squash your changes into one commit (or a few but that is more complicated to do). Instead of having several commits with similar messages you could make one bit commit. Let me know if you want to level up your `git` skills, if not we can also merge this as is. Below the line are the instructions for squashing.

---

I always look up how to do this [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes). Should be `git rebase -i HEAD~6`, then select `squash` for all but the first commit, and you are good to go. You will have to do `git push -f` as you are rewriting history :)

**Comment by betatim** [comment]
(also if you are ready, change the title of the PR from `[WIP]...` to `[MRG]...`

**Comment by jtsmith2** [comment]
Awesome,  Thanks for the Git help.  I think I got everything squashed and Circle and Travis should finish up soon.

**Comment by betatim** [comment]
Merging ... ✨ ✨ ✨ ✨ 

Congratulations to your first PR and thanks for contributing.

**Comment by glouppe** [comment]
Thanks a lot Taylor!

**Pull request merged**
